Make infer binary runnable on Mojave without fiddling with SDKROOT
Summary:
TL;DR: Until this patch, if you ran infer on MacOS Mojave you most
likely would get an error related to missing header files. Now infer
tries to automatically locate current MacOS SDK path thus providing a
better experience for first time users.

Consider helloworld.c
```
#include <stdio.h>
int main()
{
	return 0;
}
```
Invoking the analysis `infer -- cc -c helloworld.c` fails with

facebook-clang-plugins/.../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found

The reason for this is twofold:
1. infer uses its own clang, not Apple's one (thus custom paths are
not properly setup).
2. Apple stopped copying standard headers from SDK to /usr/include.

Reviewed By: jvillard

Differential Revision: D16377866

fbshipit-source-id: c336ad64f