[yojson] open builtins
Summary:
In upgrading to OCaml 5.2, yojson needs to be upgraded. The target version (0.16) does not open automatically the module with yojson builtins, so the build breaks with errors of the form
```
File "src/IR/Typ.ml", line 125, characters 17-21:
125 |   ; is_volatile: bool }
                       ^^^^
Error: Unbound value yojson_of_bool
```
This diff opens the builtins module via dune where needed.

Reviewed By: geralt-encore

Differential Revision:
D66297493

Privacy Context Container: L1208441

fbshipit-source-id: fbf4c54e52a3255ac8d75a6d58e7bd45666ad046