Fix to build on linux with glibc 2.24.
Add ifdef to avoid following error while building on latest stable glibc (2.24):

    clang -c -w libc_basic.c -o libc_basic.o
    libc_basic.c:692:12: error: unknown type name '__WAIT_STATUS'
    pid_t wait(__WAIT_STATUS stat_loc) {
            ^
In glibc 2.24, __WAIT_STATUS was replaced with 'int *':
https://github.com/bminor/glibc/commit/b49ab5f4503f36dcbf43f821f817da66b2931fe6

This is referred to as the 'union wait' removal in the release
changelog.

The fix involves checking for glibc >= 2.24 with __GLIBC_PREREQ.