[pulse] model lambda captures
Summary:
When a lambda gets created, record the abstract addresses it captures, then
complain if we see some of them be invalidated before it is called.

Add a notion of "allocator" for reporting better messages. The messages are
still a bit sucky, will need to improve them more generally at some point.

```
 jul   lambda  ~  infer  1  infer -g --pulse-only -- clang -std=c++11 -c infer/tests/codetoanalyze/cpp/pulse/closures.cpp
Logs in /home/jul/infer.fb/infer-out/logs
Capturing in make/cc mode...
Found 1 source file to analyze in /home/jul/infer.fb/infer-out

Found 2 issues

infer/tests/codetoanalyze/cpp/pulse/closures.cpp:21: error: USE_AFTER_DESTRUCTOR
  `&(f)` accesses address `s` captured by `&(f)` as `s` invalidated by destructor call `S_~S(s)` at line 20, column 3 past its lifetime (debug: 5).
  19.       f = [&s] { return s.f; };
  20.     } // destructor for s called here
  21. >   return f(); // s used here
  22.   }
  23.

infer/tests/codetoanalyze/cpp/pulse/closures.cpp:30: error: USE_AFTER_DESTRUCTOR
  `&(f)` accesses address `s` captured by `&(f)` as `s` invalidated by destructor call `S_~S(s)` at line 29, column 3 past its lifetime (debug: 8).
  28.       f = [&] { return s.f; };
  29.     }
  30. >   return f();
  31.   }
  32.

Summary of the reports

  USE_AFTER_DESTRUCTOR: 2
```

Reviewed By: da319

Differential Revision: D13400074

fbshipit-source-id: 3c68ff4ea